version: 2

builds:
  - main: .
    binary: pipe
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "pipe-{{.Version}}-{{.Os}}-{{.Arch}}"

brews:
  - directory: Formula
    repository:
      owner: getpipe-dev
      name: homebrew-pipe
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/getpipe-dev/pipe
    description: CI-friendly pipeline runner inspired by Taskfile
    license: MIT
    install: |
      bin.install "pipe"
    test: |
      assert_match version.to_s, shell_output("#{bin}/pipe --version")

changelog:
  sort: asc
